# Generated by Django 5.0.6 on 2026-04-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Cliente')),
                ('contract_type', models.CharField(choices=[('RENTAL', 'Alquiler'), ('NDA', 'Confidencialidad (NDA)')], default='RENTAL', max_length=10, verbose_name='Tipo')),
                ('pdf_file', models.FileField(upload_to='contracts/%Y/%m/', verbose_name='Archivo PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('CLEAN', 'Limpio'), ('FLAGGED', 'Banderas Rojas'), ('ERROR', 'Error')], default='PENDING', max_length=12, verbose_name='Estado')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Abogado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto extraido del PDF')),
                ('key_data', models.JSONField(default=dict, help_text='Firmantes, DNIs, fechas, importes, duracion, etc.', verbose_name='Datos clave')),
                ('red_flags', models.JSONField(default=list, help_text='Lista de objetos {clausula, problema, articulo_legal, severidad}.', verbose_name='Banderas rojas')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen del informe')),
                ('processing_time_ms', models.PositiveIntegerField(default=0, verbose_name='Tiempo de procesado (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='contracts.contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Informe de Auditoria',
                'verbose_name_plural': 'Informes de Auditoria',
            },
        ),
    ]
